services:
  web:
    build: .
    container_name: christmas-wishlist
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SCHEDULER_ENABLED=false  # Scheduler runs in separate service
      - TZ=America/New_York  # Set timezone for consistent time handling
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scheduler:
    build: .
    container_name: christmas-wishlist-scheduler
    restart: unless-stopped
    command: ["scheduler"]  # Passed to entrypoint script
    environment:
      - FLASK_ENV=production
      - SCHEDULER_ENABLED=true  # Not used by scheduler_worker.py, but for clarity
      - TZ=America/New_York  # Set timezone for scheduler (affects DAILY_DIGEST_HOUR)
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
    depends_on:
      - web

volumes:
  instance:
