name: CI

on:
  push:
    branches: [ main, master, development]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=app --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.python-version == '3.13'
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Check code formatting with black
      run: |
        black --check --diff app/ tests/ config.py run.py

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 app/ tests/ config.py run.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. Max line length is 120.
        flake8 app/ tests/ config.py run.py --count --exit-zero --max-line-length=120 --statistics

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t christmas-wishlist:test .

    - name: Test Docker container starts
      run: |
        # Start container
        CONTAINER_ID=$(docker run -d --name test-container \
          -e SECRET_KEY=test-secret-key \
          -e MAIL_USERNAME=test \
          -e MAIL_PASSWORD=test \
          -e ADMIN_EMAIL=test@example.com \
          -e ADMIN_NAME="Test Admin" \
          christmas-wishlist:test)

        echo "Container ID: $CONTAINER_ID"

        # Wait for container to initialize (with timeout)
        echo "Waiting for container to start..."
        for i in {1..30}; do
          if docker ps --filter "id=$CONTAINER_ID" --format "{{.Status}}" | grep -q "Up"; then
            echo "Container is running!"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "ERROR: Container failed to start within 30 seconds"
            docker ps -a
            docker logs test-container
            exit 1
          fi
          sleep 1
        done

        # Wait for app to be ready (check if gunicorn started)
        echo "Waiting for gunicorn to start..."
        for i in {1..15}; do
          if docker logs test-container 2>&1 | grep -q "Booting worker"; then
            echo "Gunicorn workers started!"
            break
          fi
          if [ $i -eq 15 ]; then
            echo "WARNING: Gunicorn workers not detected in logs"
          fi
          sleep 1
        done

        # Verify container is still running
        if ! docker ps --filter "id=$CONTAINER_ID" --format "{{.Status}}" | grep -q "Up"; then
          echo "ERROR: Container stopped running"
          docker ps -a
          docker logs test-container
          docker stop test-container 2>/dev/null || true
          docker rm test-container 2>/dev/null || true
          exit 1
        fi

        # Show container info
        echo "Container is healthy:"
        docker ps --filter "id=$CONTAINER_ID"

        # Check logs for startup
        echo "Container logs:"
        docker logs test-container

        # Check for errors in logs
        if docker logs test-container 2>&1 | grep -i "error\|exception\|traceback" | grep -v "fail_ci_if_error"; then
          echo "WARNING: Errors found in container logs (shown above)"
        fi

        # Cleanup
        echo "Cleaning up..."
        docker stop test-container
        docker rm test-container
